run:
  timeout: 10m
  build-tags:
    - containers_image_openpgp
    - exclude_graphdriver_btrfs
    - exclude_graphdriver_devicemapper

linters:
  enable:
    - depguard
    - gofmt
    - goimports
    - revive
    - govet
    - importas
    - ineffassign
    - misspell
    - typecheck
    - errname
    - makezero
    - whitespace
    - unused
    - forbidigo
  disable-all: true

linters-settings:
  depguard:
    rules:
      main:
        list-mode: lax
        deny:
          - pkg: io/ioutil
            desc: The io/ioutil package has been deprecated. https://go.dev/doc/go1.16#ioutil
  forbidigo:
    forbid:
      - '^fmt\.Errorf(# use errors\.Errorf instead)?$'
  importas:
    no-unaliased: true

issues:
  exclude-rules:
    - linters:
        - revive
      text: "stutters"
